# Generated by Django 5.2.6 on 2025-09-17 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_type', models.CharField(choices=[('GENERAL', 'General'), ('PROFORMA', 'Proforma')], default='GENERAL', max_length=10)),
                ('vehicle', models.CharField(blank=True, max_length=255)),
                ('lic_no', models.CharField(blank=True, max_length=50, verbose_name='Lic#')),
                ('chassis_no', models.CharField(blank=True, max_length=100, verbose_name='Chassis#')),
                ('date', models.DateField()),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.client')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('labour_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('parts_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.invoice')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
