# Generated by Django 5.2.6 on 2025-09-18 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="proforma_cc_rating",
            field=models.CharField(blank=True, max_length=50, verbose_name="CC Rating"),
        ),
        migrations.AddField(
            model_name="invoice",
            name="proforma_colour",
            field=models.CharField(blank=True, max_length=50, verbose_name="Colour"),
        ),
        migrations.AddField(
            model_name="invoice",
            name="proforma_currency",
            field=models.CharField(
                blank=True, default="JMD", max_length=10, verbose_name="Currency"
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="proforma_make",
            field=models.CharField(blank=True, max_length=100, verbose_name="Make"),
        ),
        migrations.AddField(
            model_name="invoice",
            name="proforma_model",
            field=models.CharField(blank=True, max_length=100, verbose_name="Model"),
        ),
        migrations.AddField(
            model_name="invoice",
            name="proforma_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                verbose_name="Total Cost",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="proforma_year",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Year"
            ),
        ),
    ]
