# Generated by Django 5.2.6 on 2025-09-22 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_invoice_drive_download_link_invoice_drive_file_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppSettings",
            fields=[
                (
                    "singleton_id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("global_follow_up_days", models.PositiveIntegerField(default=90)),
                (
                    "message_template",
                    models.TextField(
                        default="Hi {client_name}, just checking in from {business_name}! It's been {days_since_service} days since we last serviced you on {last_service_date}. Let us know if you need anything."
                    ),
                ),
                (
                    "business_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
            ],
            options={
                "verbose_name": "WhatsApp settings",
            },
        ),
        migrations.CreateModel(
            name="WhatsAppFollowUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_service_date", models.DateField(blank=True, null=True)),
                (
                    "follow_up_days_override",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("next_follow_up_date", models.DateField(blank=True, null=True)),
                ("last_sent_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whatsapp_follow_up",
                        to="core.client",
                    ),
                ),
            ],
            options={
                "ordering": ["client__name"],
            },
        ),
        migrations.CreateModel(
            name="WhatsAppMessageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("sent", "Sent"), ("failed", "Failed")], max_length=20
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[("manual", "Manual"), ("scheduled", "Scheduled")],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("body", models.TextField()),
                ("twilio_sid", models.CharField(blank=True, max_length=255)),
                ("error_message", models.TextField(blank=True)),
                (
                    "follow_up",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="core.whatsappfollowup",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
