# Generated by Django 5.2.6 on 2025-09-23 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_whatsappsettings_whatsappfollowup_whatsappmessagelog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="whatsappsettings",
            name="message_template",
        ),
    ]
