# Generated by Django 5.2.6 on 2026-02-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_whatsappsettings_message_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='engine_no',
            field=models.CharField(blank=True, max_length=100, verbose_name='Engine#'),
        ),
    ]
