# Generated by Django 5.2.6 on 2026-04-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_engine_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_number',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('GENERAL', 'General'), ('PROFORMA', 'Proforma'), ('REGULAR', 'Regular')], default='GENERAL', max_length=10),
        ),
    ]
